# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb5f540a6655b41f0a0760015e6d3168ae491adcb54efd9a5026c895fae3a5c9c3d04e81911b447548a8cd8000c1dffdeb4a564b697104ce75541045044f1c15

test:
  secret_key_base: 4a674cf759bdff517355cff0da3edb781c82f968c1969433d7d0230363bda3b5cd23b52fa6d809392e050ebcf1f06330049cfa609f7a4879899bcb221a4750d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
